# Generated by Django 5.0.1 on 2024-01-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_profile.customerprofile')),
            ],
            options={
                'db_table': 'ec_otp',
            },
        ),
    ]
