# Generated by Django 5.0.1 on 2024-01-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_customerotp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerotp',
            table='ec_customer_otp',
        ),
    ]
