# Generated by Django 5.0.1 on 2024-01-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(db_column='auth_access_token', null=True)),
                ('refresh_token', models.TextField(db_column='auth_refresh_token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ec_admin_auth_tokens',
            },
        ),
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(db_column='auth_access_token', null=True)),
                ('refresh_token', models.TextField(db_column='auth_refresh_token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ec_auth_tokens',
            },
        ),
    ]
